config/routes.rb
Rails.application.routes.draw do
root 'static_pages#home'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  patch '/select_form', to: 'displaydates#update'
  resources :users
  resources :posts
  resources :punches
end

=begin

=end

app/models/punch.rb
class Punch < ApplicationRecord
  belongs_to :user
  validates :user_id, presence: true
  validates :punch_at_in, presence: true
  validates :status, presence: true
end

app/controllers/punches_controller.rb
class PunchesController < ApplicationController
  before_action :correct_user, only: [:edit, :update]
  before_action :reset_today, only: [:create, :update]
  before_action :reset_show_params, only: [:index]

  def index
    @punches = Punch.where(punch_date: choice_date)
  end

  def create
    user = User.find_by(id: params[:punch][:user_id])
    @user = user
    if user && user.authenticate(params[:punch][:password])
      if logged_in?
        log_out
        log_in user
      else
        log_in user
      end
      if params[:punch][:status] == "in"  
        if already_punch_in?  
          flash[:error] = "本日の出社時間はすでに打刻済みです"
          redirect_to '/punches'
        else 
          @punch = @user.punches.new(status: params[:punch][:status], 
                                     punch_at_in: Time.new,
                                     punch_date: Time.new)
          if @punch.save 
            flash[:success] = "打刻が完了しました"
            redirect_to '/punches'
          end
        end
      else  
        if already_punch_out?
          flash[:error] = "本日の退社時間はすでに打刻済みです"
          redirect_to '/punches'
        else
          punches = Punch.where(user_id: params[:punch][:user_id])
          @punch = punches.find_by(punch_date: Time.new) 
          @punch.update_attributes(status: "out", punch_at_out: Time.new)
          if @punch.save  
            flash[:success] = "打刻が完了しました"
            redirect_to '/punches'
          end
        end
      end
    else
      flash[:error] = "アカウントが未選択、またはパスワードが正しくありません"
      redirect_to root_url
    end
  end

  def edit
    @punch = Punch.find_by(id: params[:id])
    if params[:edit] == "in" 
      session[:punch_at] = "in"
    else  
      session[:punch_at] = nil
    end
  end

  def update
    @punch = Punch.find_by(id: params[:id])
    if session[:punch_at] == "in" 
      @punch.punch_at_in = Time.zone.local(params[:punch]["punch_at_in(1i)"].to_i, params[:punch]["punch_at_in(2i)"].to_i, params[:punch]["punch_at_in(3i)"].to_i, params[:punch]["punch_at_in(4i)"].to_i, params[:punch]["punch_at_in(5i)"].to_i)
      @punch.punch_date = Time.zone.local(params[:punch]["punch_at_in(1i)"].to_i, params[:punch]["punch_at_in(2i)"].to_i, params[:punch]["punch_at_in(3i)"].to_i)
    else  
      @punch.punch_at_out = Time.zone.local(params[:punch]["punch_at_out(1i)"].to_i, params[:punch]["punch_at_out(2i)"].to_i, params[:punch]["punch_at_out(3i)"].to_i, params[:punch]["punch_at_out(4i)"].to_i, params[:punch]["punch_at_out(5i)"].to_i)
    end
    if @punch.save
      flash[:success] = "打刻時間を更新しました"
      redirect_to '/punches'
    else
      render 'edit'
    end
  end

  def destroy
    Punch.find(params[:id]).destroy
    flash[:success] = "打刻を削除しました"
    redirect_to root_url
  end
  
  # 今日の打刻がすでに存在するかどうかを判別する
  def already_punch_in?
    punch = Punch.find_by(user_id: params[:punch][:user_id], punch_date: Time.new)
    !punch.nil?
  end
  
  def already_punch_out?
    punch = Punch.find_by(user_id: params[:punch][:user_id], punch_date: Time.new)
    !punch.punch_at_out.nil?
  end
  
  # beforeアクション
  
  def correct_user
    punch = Punch.find_by(id: params[:id])
    user_id = punch.user_id
    @user = User.find(user_id)
    redirect_to(root_url) unless current_user?(@user)
  end
  
  def reset_show_params
    session[:show_page] = nil
  end
end

app/helpers/punches_helper.rb
module PunchesHelper
  
  def punch_at_session_in?
    !session[:punch_at].nil?
  end
  
  # 記録した時間の年日を省いて単位を「時分」表示にする
  def to_time(punch)
    punch.strftime("%-k時%-M分")
  end
  
  # 記録した時間の時分を省いて単位を「年月日」表示にする
  def to_date(punch)
    punch.strftime("%Y年%-m月%-d日")
  end
  
  # プロフィールページにいるときはtrue
  def user_page?
    !session[:page].nil?
  end
end

app/views/punches/edit.html.erb
<% provide(:title, 'Time table') %>
<div class="container">
  <div>
    <h1>打刻時間の変更</h1>
    <div class="punch-time-edit">
      <div class="punch-edit-form">
        <%= form_for(@punch) do |f| %>
        <%= render 'shared/error_messages', object: f.object %>
        <% if punch_at_session_in? %>
          <%= f.label :punch_at_in, "出社時間" %>
          <div class="before-punch-edit">
            <a>変更前</a><%= to_time(@punch.punch_at_in) %>
          </div>
          <div class="punch-edit-select-form">
            <%= f.datetime_select :punch_at_in, minute_step: 5, default: @punch.punch_at_in %>
          </div>
        <% else %>
          <%= f.label :punch_at_out, "退社時間" %>
          <% if @punch.punch_at_out %>
            <div class="before-punch-edit">
              <a>変更前</a><%= to_time(@punch.punch_at_out) %>
            </div>
            <div class="punch-edit-select-form">
              <%= f.datetime_select :punch_at_out, minute_step: 5, default: @punch.punch_at_out %>
            </div>
          <% else %>
            <div class="punch-edit-select-form">
              <%= f.datetime_select :punch_at_out, minute_step: 5, include_blank: true %>
            </div>
          <% end %>
        <% end %>
        <div class="punch-edit-btn">
          <%= f.submit "更新", class: "btn btn-primary" %>
          <%= link_to "削除", punch_path, method: :delete, data: { confirm: "一覧から一日分の打刻を削除します。よろしいですか？" } %>
        </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/punches/index.html.erb
<% provide(:title, 'PunchList') %>
<div class="container">
  <div>
    <div class="list-top">
      <div class="back-btn">
      </div>
      <%= render 'displaydates/select_form' %>
    </div>
    <div class="list-bottom">
      <%= render 'shared/punch_list' %>
    </div>
  </div>
</div