config/routes.rb
Rails.application.routes.draw do
root 'static_pages#home'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  patch '/select_form', to: 'displaydates#update'
  resources :users
  resources :posts
  resources :punches
end

=begin

=end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
  <ul>
  <% object.errors.full_messages.each do |msg| %>
  <li>><%= msg %></li>
  <% end %>
  </ul>
<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
  <ol class="posts">
    <%= render @feed_items %>
  </ol>
  <%= will_paginate @feed_items %>
<% end %>

app/views/shared/_post_form.html.erb
<div class="posts-index-left list">
  <div class="post-user-inf">
    <%= link_to user_img(@post.user), @post.user %>
    <%= link_to @post.user.name, @post.user %>
  </div>
  <%= form_for @post do |f| %>
    <%= render 'shared/error_messages', object: f.object %>
    <div class="post-field">
      <%= f.text_area :content, placeholder: "なにかつぶやいてみる..." %>
    </div>
    <div class="post-picture">
      <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
    </div>
    <%= f.submit "Post", class: "btn btn-primary" %>
  <% end %>
</div>
  
  <script type="text/javascript">
    $('#post_picture').bind('change', function() {
      var size_in_megabytes = this.files[0].size/1024/1024;
      if (size_in_megabytes > 5) {
        alert('Maximum file size is 5MB. Please choose a smaller file.');
      }
    });
  </script>

app/views/shared/_punch_list.html.erb
<div class="punch-list list">
  <ul class="punch-list-title">
    <li class="user-img-name user-img-name-title">　</li>
    <li class="punch-at-in-time punch-at-in-time-title">出勤</li>
    <li class="punch-at-out-time punch-at-out-time-title">退勤</li>
  </ul>
  <% @punches.each do |punch| %>
  <ul class="punch-list-contents">
    <li class="user-img-name user-img-name-contents">
      <%= link_to user_img(punch.user), punch.user %>
      <%= link_to punch.user.name, punch.user %>
    </li>
    <div class="border"></div>
    <li class="punch-at-in-time punch-at-in-time-contents">
      <% if logged_in? && punch.user_id == current_user.id %>
        <% if session[:show_page] == "stamps" %>
          <%= link_to "#{to_date(punch.punch_at_in)}#{to_time(punch.punch_at_in)}", edit_punch_path(punch, edit: 'in') %>
        <% else %>
          <%= link_to "#{to_time(punch.punch_at_in)}", edit_punch_path(punch, edit: 'in') %>
        <% end %>
      <% else %>
        <%= to_time(punch.punch_at_in) %>
      <% end %>
    </li>
    <div class="border"></div>
    <li class="punch-at-out-time punch-at-out-time-contents">
      <% if punch.punch_at_out %>
        <% if logged_in? && punch.user_id == current_user.id %>
          <% if session[:show_page] == "stamps" %>
            <%= link_to "#{to_date(punch.punch_at_out)}#{to_time(punch.punch_at_out)}", edit_punch_path(punch, edit: 'out') %>
          <% else %>
            <%= link_to "#{to_time(punch.punch_at_out)}", edit_punch_path(punch, edit: 'out') %>
          <% end %>
        <% else %>
          <%= to_time(punch.punch_at_out) %>
        <% end %>
      <% else %>
        <p>no punch</p>
      <% end %>
    </li>
  </ul>
  <% end %>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size: 50), current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "プロフィール", current_user %></span>
<span><%= pluralize(current_user.posts.count, "post") %></span>