config/routes.rb
Rails.application.routes.draw do
root 'static_pages#home'
  get '/about',     to: 'static_pages#about'
  get '/contact',   to: 'static_pages#contact'
  get '/signup',    to: 'users#new'
  get '/login',     to: 'sessions#new'
  post '/login',    to: 'sessions#create'
  delete '/logout', to: 'sessions#destroy'
  patch '/select_form', to: 'displaydates#update'
  resources :users
  resources :posts
  resources :punches
end

=begin

=end

app/views/layouts/_flash.html.erb
<% flash.each do |message_type, message| %>
  <div class="alert alert-<%= message_type %>"><%= message %></div>
<% end %>

app/views/layouts/_head.html.erb
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= analytics_init if Rails.env.production? %>
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>

app/views/layouts/_header.html.erb
<header>
  <div>
    <nav>
      <ul class="header-menus header-menus-left">
        <li><%= link_to "Home", root_path %></li>
        <li><%= link_to "About", about_path %></li>
      </ul>
    </nav>
    <%= link_to root_path, id: "logo" do %>
      <%= image_tag "PunchApp_white_logo.png" %>
    <% end %>
    <nav>
      <ul class="header-menus header-menus-right">
        <li><%= link_to "StampList", punches_path %></li>
        <% if logged_in? %>
        <li><%= link_to "Posts", posts_path %></li>
        <li class="user-dropmenu" id="dropmenu">
          <a><%= user_img(current_user) %></a><a id="down">▼</a>
          <ul>
            <li><%= link_to "マイページ", current_user %></li>
            <li><%= link_to "設定", edit_user_path(current_user) %></li>
            <li><%= link_to "ログアウト", logout_path, method: :delete %></li>
          </ul>
        </li>
        <% else %>
        <li><%= link_to "ログイン", login_path %></li>
        <% end %>
      </ul>
    </nav>
  </div>
</header>
    

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
      <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
      </script>
    <![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <%= render 'layouts/head' %>
  <%= render 'layouts/shim' %>
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="main">
      <%= render 'layouts/flash' %>
      <%= yield %>
    </div class="main">
  </body>
</html>